### ISSUE TITLE
Should Sidenotes and Marginnotes be hidden on index (and other full-width pages)?

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [clayh53/tufte-jekyll#28]
I've run into a problem with using sidenotes (and marginnotes) within the excerpted part of posts and I'd like to confirm that I'm not doing something completely stupid.

The notes are rendered on the default index and break the layout because index is full-width while posts are not. I have added the following scss as a quick fix, but it seems unlikely to me that I'm the first to run into this problem so I am wondering if I missed a more canonical way to deal with this problem.

```scss
.full-width {
  .sidenote, .sidenote-number, .marginnote  {
    display: none;
  }
}
```
