### ISSUE TITLE
Capitalisation of post titles

### ISSUE THREAD

**Issue by alpha-beta-soup** [clayh53/tufte-jekyll#41]
The case of titles is not being respected in posts:

```yaml
---
layout: post
title: "One Day in Montréal"
date: 2014-06-12 17:58:10 +1200
---
```

With very little adaptation from the demo, here is the view on the "Blog" page showing excerpts.

![screenshot from 2016-03-20 23 09 18](https://cloud.githubusercontent.com/assets/5925045/13903868/d76c6c60-eef0-11e5-8217-01d318e0634d.png)

But in the actual post the case of the title is no longer respected:

![screenshot from 2016-03-20 23 09 32](https://cloud.githubusercontent.com/assets/5925045/13903867/d762474e-eef0-11e5-8837-5934f75af0c9.png)
